### ISSUE TITLE
[Feature Request] Hide icon when no Bluetooth devices connected

### ISSUE THREAD

**Issue by yochananmarqos** [MichalW/gnome-bluetooth-battery-indicator#1]
Could you add an option in the settings to hide the icon when no device is connected?

**Comment by MichalW** [comment]
Ok, but won't it be a problem to click on settings if there is no icon?

**Comment by yochananmarqos** [comment]
No, because the settings can be accessed via the Extensions application.

**Comment by Pioxis** [comment]
Również przyłączam się do propozycji. Bardzo dobra robota z tym dodatkiem. A autoukrywanie ikon kiedy nic nie jest podpięte będzie dobrym rozwiązaniem. Tak samo dodatkowo mogłaby się pojawiać ikona tylko podłączonego urządzenia. Kiedy mam myszkę i słuchawki po BT, a podłączam tylko myszkę to byłoby fajnie jakby słuchawki się nie pojawiały jako pusta ikona.

**Comment by yochananmarqos** [comment]
Thanks for implementing it!
