### ISSUE TITLE
How can I manually change the port?

### ISSUE THREAD

**Issue by Kronodile** [MichalW/gnome-bluetooth-battery-indicator#13]
Port 1 always works for me with pythonscript on my JBL T460BT, but the extension doesn't work initially. When I run the python script again, the extensions starts working perfectly. How can I edit the port to 1 in the extension? Please help me out.

Thanks!
My OS: Manjaro
Headset: JBL T460BT

**Comment by MichalW** [comment]
We have to create an optional field in settings to set up a port for each device

**Comment by MichalW** [comment]
@Kronodile Please check if it works now :)
