### ISSUE TITLE
Error starting extension

### ISSUE THREAD

**Issue by jorgerabello3** [MichalW/gnome-bluetooth-battery-indicator#14]
After installing the extension the following error occurs:

SyntaxError: invalid property id

Stack trace:
  @/home/jorge-augusto-pinto/.local/share/gnome-shell/extensions/bluetooth-battery@michalw.github.com/settingsWidget.js:6:7
  @/home/jorge-augusto-pinto/.local/share/gnome-shell/extensions/bluetooth-battery@michalw.github.com/prefs.js:10:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

S.O: Ubuntu 18.04 LTS 64 bits
Gnome Shell Version: 3.28.4

Thanks xD

**Comment by MichalW** [comment]
@jorgerabello3 Does this problem still occur?

**Comment by jorgerabello3** [comment]
Hi @MichalW thanks for the reply and attention. Not anymore, I'm ending the issue ok? I've been investigating and realized that it was a problem in my s.o. which was resolved after upgrading to a newer version.

Thank you very much!!!
