### ISSUE TITLE
Missing bluetooth_battery Python module

### ISSUE THREAD

**Issue by yochananmarqos** [MichalW/gnome-bluetooth-battery-indicator#2]
The [`bluetooth-battery`](https://pypi.org/project/bluetooth-battery/) Python module needs to be installed. The `bluetooth_battery.py` script you dumped into the extension folder will not work by itself. It [looks for](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/blob/master/bluetooth_battery.py#L12) it's module and can't find it.

**Comment by MichalW** [comment]
Did you install this package by https://extensions.gnome.org?
If you have cloned git repo then you need to do: `git submodule update --init`

**Comment by yochananmarqos** [comment]
I tried both and did init the submodule.

I just realized I was wrong and what was actually missing was `pybluez` as it's a dependency of `bluetooth_battery`.

**Comment by MichalW** [comment]
Do you have an Ubuntu?
Please try instruction from the Readme:
```
sudo apt install bluez libbluetooth-dev python3-dev
```

**Comment by yochananmarqos** [comment]
I'm using Manjaro GNOME. I already installed `python-pybluez` )and it's working fine. What I meant was the dependency is missing from your `README`.

**Comment by MichalW** [comment]
Would you like to add instructions for Manjaro GNOME to readme?

**Comment by yochananmarqos** [comment]
I was thinking of adding it to the AUR, I'll make a PR if I do.

You seem to be missing what I'm trying to tell you. [`bluetooth-battery`](https://pypi.org/project/bluetooth-battery/)  depends on [`pybluez`](https://pypi.org/project/pybluez/) no matter what distro one is using as they're Python packages. I'm wondering if you've already installed `pybluez` with Pip or APT. That's also the name of the Debian / Ubuntu package.
