### ISSUE TITLE
GNOME 41 support

### ISSUE THREAD

**Issue by tyunn** [MichalW/gnome-bluetooth-battery-indicator#26]
Hello! 
Thanks for this great tool!
Please add support for GNOME 41, because In the extensions page https://extensions.gnome.org/extension/3991/bluetooth-battery/ this extension is outdated. 
Thanks in advance!

**Comment by Etaash-mathamsetty** [comment]
it should probably work with gnome 41, you just have to modify metadata.json in the extension's folder

**Comment by MichalW** [comment]
I updated the metadata. When the update comes, please let me know if it works :)

**Comment by tyunn** [comment]
Thank you!) But apparently it didn't help.
I was able to install extension by [https://extensions.gnome.org/](url), and headphone icon appeared on the panel, but, unfortunettely, after connect bluetooth headphones, battery level information was not displayed. I tried both positions of the "Get battrey levels using bluetoothctl" switch.

**Comment by tyunn** [comment]
Hm, in my case, I need only install `pip install bluetooth_battery` and now indicator is show percentage

**Comment by alfabuster** [comment]
Still not

> I updated the metadata. When the update comes, please let me know if it works :)

What about supporting Gnome 42.1?

![Bluetooth-battery](https://user-images.githubusercontent.com/18118824/169594301-102d8ec4-26f4-444c-95e7-ab2da26610e3.png)

**Comment by Etaash-mathamsetty** [comment]
> Still not
> 
> > I updated the metadata. When the update comes, please let me know if it works :)
> 
> What about supporting Gnome 42.1?
> 
> ![Bluetooth-battery](https://user-images.githubusercontent.com/18118824/169594301-102d8ec4-26f4-444c-95e7-ab2da26610e3.png)

I no longer use gnome, but I was using this: https://extensions.gnome.org/extension/1401/bluetooth-quick-connect/ (it shows battery level too)
instead of bluetooth battery indicator (since it's not as good tbh)
