### ISSUE TITLE
Failed with error for Ubuntu Focal Fossa for the latest version (22)

### ISSUE THREAD

**Issue by kred-jon** [MichalW/gnome-bluetooth-battery-indicator#35]
Not running for the latest version on Ubuntu with GNOME Shell 3.36.9

**Comment by kred-jon** [comment]
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5a00007
JS WARNING: [resource:///org/gnome/shell/misc/extensionUtils.js 217]: reference to undefined property "metadata"
JS ERROR: Extension bluetooth-battery@michalw.github.com: SyntaxError: fields are not currently supported @ /home/user/.local/share/gnome-shell/extensions/bluetooth-battery@michalw.github.com/extension.js:139
JS ERROR: Extension bluetooth-battery@michalw.github.com: SyntaxError: fields are not currently supported @ /home/user/.local/share/gnome-shell/extensions/bluetooth-battery@michalw.github.com/extension.js:139

**Comment by kred-jon** [comment]
so we need to downgrade the version to V19 or V10

**Comment by kred-jon** [comment]
Yes, maybe the UPower script got bugs, now I'm running 3.38 v19. Its working now, not to upgrade it to next version for now.

**Comment by eirik-ff** [comment]
I have the same problem, i.e. `SyntaxError: fields are not currently supported @ [...]/extension.js:139`. The UPower script returns the expected result for me. As the error is a `SyntaxError`, the error must be in the javascript, not in any external scripts. I don't know enough javascript to know how to fix the error, though. 

My versions:
* GNOME Shell 3.36.9
* gjs 1.64.5
* Ubuntu 20.04.4 LTS

**Comment by eirik-ff** [comment]
I fixed the issue for me by redefining the function `_setPercentFromScript` to be a function and not a member/field. See PR #39.

**Comment by 53R3n17Y-serenity** [comment]
> I fixed the issue for me by redefining the function `_setPercentFromScript` to be a function and not a member/field. See PR #39.
> 
> Please, can @kred-jon and @53R3n17Y-serenity confirm that it works for them aswell?

v25 works for me, thank you @eirik-ff 
Updated through [Bluetooth battery indicator - GNOME Shell Extensions](https://extensions.gnome.org/extension/3991/bluetooth-battery/ "Bluetooth battery indicator - GNOME Shell Extensions")
Checked metadata.json

![Bluetooth battery indicator ](https://user-images.githubusercontent.com/100675600/160704681-04039ea6-a5e2-44c2-9a92-c1e8ab102c54.png)

**Comment by kred-jon** [comment]
Great work! it's fixed now!! thanks to eirik-ff

![Unsaved Image 2](https://user-images.githubusercontent.com/38023611/160952474-9f7e0aec-832e-496a-be82-73c7fa1fe934.png)

**Comment by eirik-ff** [comment]
Glad to hear it works for you too! It'd be great if you could mark the issue as resolved now. :)

**Comment by kred-jon** [comment]
An update,
The best stable things I do now just tuning in the Upower script. /scripts/upower_battery.sh and make use Pulseaudio logs in Ubuntu. This stable until now version. *add the line 7 and disable the existing line 4.

`1	#!/bin/bash
       
     2	# awk explaination: https://stackoverflow.com/questions/13534306/how-can-i-set-the-grep-after-context-to-be-until-the-next-blank-line
     3	# grep explaination: https://stackoverflow.com/questions/1546711/can-grep-show-only-words-that-match-search-pattern
     4	#percent=$(upower --dump | tr '[:lower:]' '[:upper:]' | awk "/$1/" RS= | grep -oE '[0-9]{1,3}%')
     5	connected=$(bluetoothctl info $1 | grep "Connected" | cut -d ' ' -f2)
     6	#replace percent to run from syslog pulseaudio
     7	percent=$(more /var/log/syslog |grep "Battery Level" |tail -1 |cut -b 60-65)
     8	if [[ $connected == "yes" ]]; then
     9	  if [ -z "$percent" ]; then
    10	    echo "?"
    11	  else
    12	    echo "$percent"
    13	  fi
    14	elif [[ $connected == "no" ]]; then
    15	  echo "off"
    16	else
    17	  echo "?"
    18	fi
`
