### ISSUE TITLE
Add AirPods support

### ISSUE THREAD

**Issue by humbertogontijo** [MichalW/gnome-bluetooth-battery-indicator#36]
Could you add AirPods support? There is a repo that actually works for AirPods: https://github.com/delphiki/AirStatus
For some reason the AIRPODS_DATA_LENGTH do not match in my case, but if the length is ignored the data is there and working

**Comment by matan129** [comment]
See https://github.com/MichalW/gnome-bluetooth-battery-indicator/issues/27#issuecomment-1234774149

**Comment by anlsergio** [comment]
> See [#27 (comment)](https://github.com/MichalW/gnome-bluetooth-battery-indicator/issues/27#issuecomment-1234774149)

@matan129 I cloned and installed it from your repo and it doesn't seem to work. I mean, by running the AirStatus Python script directly it runs with no errors, but nothing is printed out in the console output whatsoever.

I wonder if that's something to do with the version of my Airpods Pro (gen 3)
