### ISSUE TITLE
Update for Ubuntu 22.04

### ISSUE THREAD

**Issue by Era-Dorta** [MichalW/gnome-bluetooth-battery-indicator#44]
I see no icon in ubuntu 22.04 and when I run the test script https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/blob/master/bluetooth_battery.py I get the following error if I'm not connected to the device
```
Traceback (most recent call last):
  File "/home/era/./bluetooth_battery.py", line 166, in <module>
    main()
  File "/home/era/./bluetooth_battery.py", line 163, in main
    print("Battery level for {} is {}".format(device, str(query)))
  File "/home/era/./bluetooth_battery.py", line 93, in __str__
    return "{:.0%}".format(self._perform_query() / 100)
  File "/home/era/./bluetooth_battery.py", line 105, in _perform_query
    sock.send(b"+BRSF: 1024")
  File "/home/era/./bluetooth_battery.py", line 66, in send
    return super().send(b"\r\n" + data + b"\r\n")
  File "<string>", line 3, in send
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
``` 
and this one if I'm connected
```
Traceback (most recent call last):
  File "<string>", line 3, in connect
_bluetooth.error: (16, 'Device or resource busy')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/era/./bluetooth_battery.py", line 166, in <module>
    main()
  File "/home/era/./bluetooth_battery.py", line 163, in main
    print("Battery level for {} is {}".format(device, str(query)))
  File "/home/era/./bluetooth_battery.py", line 93, in __str__
    return "{:.0%}".format(self._perform_query() / 100)
  File "/home/era/./bluetooth_battery.py", line 101, in _perform_query
    sock.connect(self._bt_settings)
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: [Errno 16] Device or resource busy

```

**Comment by kred-jon** [comment]
The best stable things I do now just tuning in the Upower script. /scripts/upower_battery.sh and make use Pulseaudio logs in Ubuntu. This stable until now version. *add the line 7 and disable the existing line 4.

`#!/bin/bash

# awk explaination: https://stackoverflow.com/questions/13534306/how-can-i-set-the-grep-after-context-to-be-until-the-next-blank-line
# grep explaination: https://stackoverflow.com/questions/1546711/can-grep-show-only-words-that-match-search-pattern
#percent=$(upower --dump | tr '[:lower:]' '[:upper:]' | awk "/$1/" RS= | grep -oE '[0-9]{1,3}%')
connected=$(bluetoothctl info $1 | grep "Connected" | cut -d ' ' -f2)
#replace percent to run from syslog pulseaudio
percent=$(more /var/log/syslog |grep "Battery Level" |tail -1 |cut -b 60-65)
if [[ $connected == "yes" ]]; then
  if [ -z "$percent" ]; then
    echo "?"
  else
    echo "$percent"
  fi
elif [[ $connected == "no" ]]; then
  echo "off"
else
  echo "?"
fi
`

**Comment by JadeVane** [comment]
This may not be a bluetooth battery issue, try running `bluetooth info` and you may not find any power related data in the results.

Since bluez does not show the battery level of bluetooth devices by default, but it has an experimental feature that supports battery queries and must be enabled manually, try running the following command

```bash
sudo sed -i '/[General]/a\Experimental=true' /etc/bluetooth/main.conf
systemctl restart bluetooth
```

At this point the bluetooth device will be disconnected, just reconnect it manually

Then enable the `upower` method of querying in the settings and you will see the battery info in the panel
