### ISSUE TITLE
Add support for other devices found in the gnome power menu

### ISSUE THREAD

**Issue by MKrabs** [MichalW/gnome-bluetooth-battery-indicator#46]
Would it be possible to add indicators for other devices found in the gnome power menu? It might not be a Bluetooth device, but having it show up would be very nice.

For example the mouse dongle which reports the battery level of the mouse :  
![Screenshot from 2022-08-03 13-50-29](https://user-images.githubusercontent.com/71791731/182601289-21891067-8533-4d7f-89eb-87567b2d7441.png)

Current menu:  
![Screenshot from 2022-08-03 13-50-51](https://user-images.githubusercontent.com/71791731/182601331-729de7b0-4bc7-47fb-857e-fbbfa80409ec.png)

**Comment by MichalW** [comment]
I changed the source of information and now I get all devices from upower
