### ISSUE TITLE
Icons OK but no pourcentages on ubuntu 20.04

### ISSUE THREAD

**Issue by Shaltz** [MichalW/gnome-bluetooth-battery-indicator#5]
On ubuntu 20.04 (gnome 3.36.8), the pourcentage is not displayed
just the icons...

what do you need from me to help you out fixing this ?

thx in advance

**Comment by MichalW** [comment]
Did you install the dependencies?
```
bluez libbluetooth-dev python3-dev pybluez
```

I'm using this script: 
https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level

Can you run it and tell if it returns the correct percentage?

**Comment by MichalW** [comment]
@Shaltz I have an idea what the problem could be. 
There is no latest version of the package on the extensions.gnome.org yet.

I am waiting for the latest patches to be accepted there. 
During this time you can manually install the new version by cloning this repository.

(There is a bug in the old version, and you must have all devices enabled in the settings to show up)

**Comment by MichalW** [comment]
@Shaltz Can I close this issue? It should work in the new version

**Comment by MartinzX24** [comment]
I've made a pull request with a simple/quick fix: #6 
(it worked for me)

**Comment by guiAlberto** [comment]
Looking forward for this fix. Hope the PR gets accepted soon and solves the issue.

**Comment by abelayalew** [comment]
`sudo pip install pybluez`
solved my issue :) not working perfectly !
