### ISSUE TITLE
Add support for Fedora Silverblue

### ISSUE THREAD

**Issue by m4k1fu** [MichalW/gnome-bluetooth-battery-indicator#53]
Hello how are you? I'll start by saying it's not a requirement, but if it were possible and you had the time and desire (of course), could you port the extension to Fedora Silverblue? For some unknown reason it doesn't work, I tried to find out with some users of the same system and apparently I'm not the only one with problems.
If possible I would be grateful.

**Comment by zastrixarundell** [comment]
I've been able to find a workaround:

* Go to addon settings
* Set the device status to true and source to Upower
* Turn extension off
* Turn extension on

Rare case you might need to do `rpm-ostree install upower` if it's already not in the distro.

**Comment by m4k1fu** [comment]
> I've been able to find a workaround:
> 
> * Go to addon settings
> * Set the device status to true and source to Upower
> * Turn extension off
> * Turn extension on
> 
> Rare case you might need to do `rpm-ostree install upower` if it's already not in the distro.

It now starts to show the icon, but it does not show the handset battery percentage. I changed to all possible methods, in Bluetoothctl and Upower where the percentage should be, an icon of "?" appears, already with pythonscript the icon appears but without the percentage of battery.

**Comment by zastrixarundell** [comment]
Yeah it seems that it works for my xbox controller and shows the same as in
gnome power settings. For other devices when gnome doesn't see it neither
does the extension. (3rd party controller and headset)

**Comment by m4k1fu** [comment]
I was able to show the percentage of my bluetooth headset following the steps in this post (minus step 1, logically being in fedora):
https://github.com/MichalW/gnome-bluetooth-battery-indicator/issues/52
I changed the /etc/bluetooth/main.conf file as shown in the arch wiki (item 3.4 - https://wiki.archlinux.org/title/bluetooth) enabling some experimental features and after that shazammm, it works.
