### ISSUE TITLE
Isn't is supposed to show something on the panel? (Fedora 37)

### ISSUE THREAD

**Issue by hrqmonteiro** [MichalW/gnome-bluetooth-battery-indicator#63]
[Screencast from 2023-04-14 11-51-13.webm](https://user-images.githubusercontent.com/17055027/232078455-f20c6ec4-a7a6-4087-96f1-e50241d193fe.webm)

**Comment by marxin** [comment]
I have a similar issue on openSUSE Tumbleweed with Gnome `44.0`:
![Screenshot from 2023-04-21 09-14-06](https://user-images.githubusercontent.com/2658545/233567127-3eb9f347-81d2-4126-ac9c-f075b59046e1.png)

I would really love to use your Extention!

**Comment by hrqmonteiro** [comment]
Mine was automatically fixed when updated to Fedora 38/Gnome 44

**Comment by marxin** [comment]
It works for me now, I had to switch to `bluetoothctl` mode.
