### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by darkdragon-001** [MichalW/gnome-bluetooth-battery-indicator#69]
Porting to ESM is required. See the [official porting guide](https://gjs.guide/extensions/upgrading/gnome-shell-45.html).

**Comment by onlyreportingissues** [comment]
The Gnome devs offer additional help on their [Discourse](https://discourse.gnome.org/tag/extensions) and [Matrix](https://matrix.to/#/#extensions:gnome.org) channels, if needed.

**Comment by Bitals** [comment]
Gnome 45 is out on Arch.

**Comment by Strykar** [comment]
```
error: failed to prepare transaction (could not satisfy dependencies)
:: installing gnome-shell (1:45.0-1) breaks dependency 'gnome-shell<=1:44.6' required by gnome-bluetooth-battery-indicator-git
```
Please update for Gnome 45
