### ISSUE TITLE
GNOME 40 support

### ISSUE THREAD

**Issue by yochananmarqos** [MichalW/gnome-bluetooth-battery-indicator#7]
Could you add GNOME 40 support? The preferences won't open:

```
TypeError: this.set_border_width is not a function

Stack trace:
  _init@/usr/share/gnome-shell/extensions/bluetooth-battery@michalw.github.com/settingsWidget.js:22:18
  buildPrefsWidget@/usr/share/gnome-shell/extensions/bluetooth-battery@michalw.github.com/prefs.js:17:25
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by corebots** [comment]
Indeed the extension doesn't work under GNOME 40 :(

**Comment by raffaelecervino** [comment]
I will try to make a fork for making this work with gnome 40

**Comment by abinlatheef** [comment]
> I will try to make a fork for making this work with gnome 40

Are you done? Waiting..

**Comment by MichalW** [comment]
@abinlatheef @corebots @yochananmarqos Please check if it works now :)

**Comment by yochananmarqos** [comment]
@MichalW Yes, it's working. Thanks!

**Comment by abinlatheef** [comment]
> @abinlatheef @corebots @yochananmarqos Please check if it works now :)

Thank you very much. But it is showing 'busy' for me. Sometimes changing to 'refused' and again 'busy' when I hit the refresh button.
![image](https://user-images.githubusercontent.com/63762448/129434786-b312bcf9-ed23-42a1-b17e-e1779225e338.png)
Please look into it. Sorry for bothering.
