### ISSUE TITLE
Gnome Shell 45 crashes when the extension is enabled

### ISSUE THREAD

**Issue by gerardbosch** [MichalW/gnome-bluetooth-battery-indicator#77]
Hi!

Today the Extension Manager notified me that there was an update (I was waiting for this update to support Gnome 45). Just after updating it and logging out, I face with an irrecoverable crash from the desktop environment.

Any way to troubleshoot it? I had to disable the extension with

```
gnome-extensions disable bluetooth-battery@michalw.github.com
```

**OS**: Ubuntu 23.10 (Gnome 45 / X11)

Here is the panic:

![image](https://github.com/MichalW/gnome-bluetooth-battery-indicator/assets/30733556/4719a626-b1c6-493a-bdd3-cffb3e23b5af)

**Comment by a544jh** [comment]
Having the same issue with Gnome 45 on Arch. Also using X11.

**Comment by SandHilt** [comment]
I have same problem, if you see in gnome-logs:
```
18:52:20 systemd: Failed to start Application launched by gnome-session-binary.
18:52:20 systemd: Failed to start Application launched by gnome-session-binary.
18:52:20 systemd: Failed to start Application launched by gnome-session-binary.
18:52:20 gdm-session-wor: gkr-pam: unable to locate daemon control file
18:52:14 systemd-coredum: Process 37206 (gnome-shell) of user 1000 dumped core.
```

**Comment by gerardbosch** [comment]
Hi, I've tested and the new version works fine 🎉. Thank you!!
I'm closing the issue :)
