### ISSUE TITLE
I only get battery of one device when multiple devices are present

### ISSUE THREAD

**Issue by ismasou** [MichalW/gnome-bluetooth-battery-indicator#79]
Thank you for the extension.
Recently, I've been having this issue when connecting multiple bluetooth devices.
I only get the battery of one of them, the others stay blank.
When I checked the script, it all seems to work just fine to get the battery.
I found that if I get comment out this [line](https://github.com/MichalW/gnome-bluetooth-battery-indicator/blob/2da0e1882aefbf1f56a3d8bc9ca29c71174b6bce/utils.js#L35), then it works.
```javascript
            this._cancellable.connect(() => proc.force_exit());
```
It seems that this is killing the processes before it can output the battery percentage.
Is this really needed?

**Comment by MichalW** [comment]
I have made some changes that should help with this problem
