### ISSUE TITLE
Large gap between adjacent icons

### ISSUE THREAD

**Issue by ivanmood0** [MichalW/gnome-bluetooth-battery-indicator#8]
First of all, I want to thank you for this extension, but in the extension, I would say a certain is available visual defect, which is due to the fact that between adjacent icons is a large gap, due to the fact that the extension is not hidden, but only hidden icon, and this in turn leads to the possibility of clicking on an empty space with the subsequent display of the settings menu. In my opinion, this causes some discomfort.
![bugg](https://user-images.githubusercontent.com/79835684/114243030-8de90400-9994-11eb-8db2-945ec7e17beb.png)

**Comment by MichalW** [comment]
This should solve your problem :) 
Thanks for comment
