### ISSUE TITLE
I only see the % of my headphones, even if the phone is also connected

### ISSUE THREAD

**Issue by ghost** [MichalW/gnome-bluetooth-battery-indicator#80]
Hello! Firstly want to thank you for this extension. 

The issue is that I can only see the headphones battery percentage, I can't see the phone's battery percentage.
![Screenshot from 2024-03-01 22-22-22](https://github.com/MichalW/gnome-bluetooth-battery-indicator/assets/138833621/1dadf239-ab83-4f9c-ad44-a43dd027a30e)

**Comment by MichalW** [comment]
I have made some changes that should help with this problem
