### ISSUE TITLE
[enhancement] GNOME 47 Support

### ISSUE THREAD

**Issue by iFabse** [MichalW/gnome-bluetooth-battery-indicator#86]
Are you guys looking forward to port this extension to GNOME 47?

**Comment by 4javier** [comment]
As usual, the current version of the app is actually working with Gnome 47 too.
While waiting for it to be fixed upstream you can make Gnome recognize it as compatible adding "47" to "shell-version" array of `~/.local/share/gnome-shell/extensions/bluetooth-battery@michalw.github.com/metadata.json`.
The whole file will look like this after the update:

```json
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Bluetooth battery indicator",
  "gettext-domain": "bluetooth_battery_indicator",
  "name": "Bluetooth battery indicator",
  "settings-schema": "org.gnome.shell.extensions.bluetooth_battery_indicator",
  "shell-version": [
    "45",
    "46",
    "47"
  ],
  "url": "https://github.com/MichalW/gnome-bluetooth-battery-indicator",
  "uuid": "bluetooth-battery@michalw.github.com",
  "version": 39
}
```

**Comment by iFabse** [comment]
Hey thank you @4javier. I have done this before my post and it worked. Others may avoid this deep editing and like to install it through the 'store'. It was just a reminder ;)

**Comment by MichalW** [comment]
I added versions and made a few changes. I hope it works well for you
