### ISSUE TITLE
No percentage is displayed, only the string "refused')"

### ISSUE THREAD

**Issue by RogerGodzilla** [MichalW/gnome-bluetooth-battery-indicator#9]
I currently have this plugin installed, but can't seem to get it to work. I have installed the required dependencies for Ubuntu 20.04 (which I am running). The settings menu seems to be functioning, and the icon shows up properly, but the percentage does not appear, instead being replaced by the string "refused')" without quotes. I will try a restart and update this issue after doing so.
![Image](https://user-images.githubusercontent.com/32744356/115641128-15603c80-a2de-11eb-8bf7-35ac848682f3.png)

**Comment by RogerGodzilla** [comment]
Update: rebooting had no effect

**Comment by MichalW** [comment]
What device are you connecting?

This script is based on another one:
https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level

Try to run the script `bluetooth_battery.py` from the above package manually.

**Comment by serenity-hub** [comment]
I had the same error, I clicked the icon and selected 'Refresh'.  Haven't had any issues since.

**Comment by Crucizer** [comment]
+1 
I have the same error.

**Comment by oesst** [comment]
+1
Same error with a Bose quietcomfort 35.

The command journalctl -f -o cat /usr/bin/gnome-shell prints out:

> Bluetooth battery indicator: 28:11:XXXXXX is offline (16, 'Device or resource busy')
> Bluetooth` battery indicator: 28:11:XXXXXXis offline (111, 'Connection refused')

**Comment by sesse** [comment]
I fixed QC35 (and potentially others) in the Bluetooth_Headset_Battery_Level repository, so the submodule needs to be updated (and a new release made).

**Comment by tchicotti** [comment]
+1 
same error, I give a  try in TheWeirdDev but same happens.

**Comment by darkdragon-001** [comment]
Same problem in Fedora 34.

**Comment by guiAlberto** [comment]
I am using a Ubuntu 21.04 in a ASUS S451LA and the headphone is a Pulse PH274. Same thing happens here, aldough it does not display the last characters, just the `refuesd` string.

**Comment by malomehi** [comment]
Same error with Powerbeats Pro

**Comment by MichalW** [comment]
@tchicotti @tborowy @malomehi 

In the new version, we have new settings: "Get Battery levels using bluetoothctl". 
You can try to enable it If you see percentages after using the command: "bluetoothctl info"

**Comment by tborowy** [comment]
@MichalW For me `bluetoothctl info` don't work.

**Comment by alexfornuto** [comment]
Device:Bose Soundlink AE II
OS: Pop!_OS 20.04 LTS
Not using bluetoothctl: "Refused"
Using bluetoothctl: "?"

**Comment by coldtobi** [comment]
Just an idea into a complete different direction: Gnome exports the battery values using DBus ... (https://upower.freedesktop.org/docs/UPower.html), so the parsing / enumerating could be offloaded to Gnome to reduce complexity...

**Comment by scr4bble** [comment]
Same here: Fedora 34, Headset Steelseries Arctis 9.
Dependencies installed using DNF according README in this project in addition to enabling the extension in Gnome.

Instead of percentage value:
- "refused" (even after refreshing) when using bluetoothctl is set to off
- "?" when using bluetoothctl option from extension settings (option set to on)

**Comment by kauanmocelin** [comment]
Same problem here: "refused" or "?" con bluetoothctl mode. Headphone JBL Duet NC.

**Comment by MichalW** [comment]
@RogerGodzilla @Crucizer @oesst @tchicotti @darkdragon-001 @guiAlberto @JadeVane @xicoalmeida @tborowy @malomehi @kauanmocelin 

I have uploaded a new version of this package. After updating, if you get a "refused" message, please try to use the "Force Refresh" button.

The button disconnects the device to retrieve battery information and connects the device again.

For some reason, you only need to do this once and the later battery indicator works as normal

**Comment by alexfornuto** [comment]
The updated version will not load. I wish I could give you more details, but all Gnome will say is "Error loading extension".

**Comment by alexfornuto** [comment]
Not even a full reboot resolves.

**Comment by JadeVane** [comment]
I get "refused" again, some log from `journalctl -f -o cat /usr/bin/gnome-shell` here

```
[bluetooth-battery-indicator] Using percentage source 'python-script' for device 'WH-1000XM4' (14:3F:A6:A4:85:AC).
clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
[bluetooth-battery-indicator] Percentage from script: ok

clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
[bluetooth-battery-indicator] Using percentage source 'python-script' for device 'WH-1000XM4' (14:3F:A6:A4:85:AC).
[bluetooth-battery-indicator] Percentage from script: 14:3F:A6:A4:85:AC is offline [Errno 16] Device or resource busy

[bluetooth-battery-indicator] Percentage from script: 14:3F:A6:A4:85:AC is offline [Errno 111] Connection refused

[bluetooth-battery-indicator] Percentage from script: ok

JS ERROR: TypeError: onSuccess is not a function
runPythonScript/<@/home/wenjinyu/.local/share/gnome-shell/extensions/bluetooth-battery@michalw.github.com/utils.js:53:26
```

**Comment by ismasou** [comment]
For me, I was able to make it work using `Upower` after I enabled experimental feature https://wiki.archlinux.org/title/bluetooth_headset#Battery_level_reporting

**Comment by edggoncalves** [comment]
Still getting `?` with Upower and bluetoothctl, `Connection refused` with the python script, with my XM4, on an Ubuntu 20.04.

**Comment by kred-jon** [comment]
just change the Upower script as here: https://github.com/MichalW/gnome-bluetooth-battery-indicator/issues/44#issuecomment-1233842251

**Comment by JadeVane** [comment]
This may not be a bluetooth battery issue, try running `bluetooth info` and you may not find any power related data in the results.

Since bluez does not show the battery level of bluetooth devices by default, but it has an experimental feature that supports battery queries and must be enabled manually, try running the following command

```bash
sudo sed -i '/[General]/a\Experimental=true' /etc/bluetooth/main.conf
systemctl restart bluetooth
```

At this point the bluetooth device will be disconnected, just reconnect it manually

Then enable the `upower` method of querying in the settings and you will see the battery info in the panel
